name: 'Setup Godot'
description: 'Sets Godot in the Github Actions runner enviroment'
author: 'Vitorgus'
branding:
  icon: 'play'  
  color: 'blue'
inputs:
  godot-version:
    required: true
    description: 'Godot version to download'
  mono:
    required: false
    description: 'If set to true, will download de mono version of Godot'
    default: false
  download-templates:
    required: false
    description: 'If set to false, will skip the default export templates download'
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
