name: 'Setup Godot'
description: 'Sets Godot in the Github Actions runner enviroment'
author: 'Vitorgus'
branding:
  icon: 'play'  
  color: 'blue'
inputs:
  godot-version:
    required: true
    description: 'Godot version to download'
  download-templates:
    required: false
    description: 'If it should also download and cache the export templates'
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
